### ISSUE TITLE
Sending Pojo with Map to Sink gives Codec Missing Warning

### ISSUE THREAD

**Issue by AndrewHogg** [datastax/pulsar-sink#30]
Using a Java function deployed to Pulsar to run, consuming from 1 topic and sending out on another - the Pojo defined to send out includes a HashMap<String, String>. The output topic is then consumed by the C* sink.

The sink issues this warning per message, and fails to sink to the database table.

WARN  com.datastax.oss.sink.pulsar.CassandraSinkTask - Error decoding/mapping Pulsar record PulsarSinkRecord{SinkRecord(sourceRecord=PulsarRecord(topicName=Optional[persistent://public/default/data-test.test], partition=0, message=Optional[org.apache.pulsar.client.impl.MessageImpl@5fa4b3be], schema=org.apache.pulsar.client.impl.schema.generic.GenericJsonSchema@5f601369, failFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$525/0x0000000840726840@7df5d68d, ackFunction=org.apache.pulsar.functions.source.PulsarSource$$Lambda$524/0x0000000840727440@4f680991), value=org.apache.pulsar.client.impl.schema.generic.GenericJsonRecord@31095b86)}: Codec not found for requested operation: [**Map(TEXT => TEXT, not frozen) <-> com.datastax.oss.common.sink.AbstractStruct**]

Changing the output from the function from the Pojo class to String, and converting the Pojo to Json for output, the sink then writes the message down to the table without issue.

**Comment by aymkhalil** [comment]
I'm trying to reproduce this issue locally with minimal steps. I'm bypassing topic 1 and the Pojo function and just sending the Pojo directly via a pulsar java app to the topic where the sink is configured.

@AndrewHogg what data type are you using for the C* column where you expect the HashMap<String, String> to land successfully? Also just to make sure, in your sink mapping config you are referencing the HashMap as is and not some keys inside the map, correct?

thanks.
