### ISSUE TITLE
Broken link on readme.md

### ISSUE THREAD

**Issue by chrislatimer** [datastax/pulsar-sink#5]
The link in the _Mapping specification_ section is broken:

To see practical examples and usages of mapping, see: https://docs.datastax.com/en/pulsar/doc/search.html?searchQuery=mapping

**Comment by eolivelli** [comment]
@chrislatimer we can update the link once we have the documentation site online

**Comment by johnsmartco** [comment]
Correct - the link is a "leap of faith" value that looks ahead to when the DataStax Apache Pulsar Connector docs are deployed at GA (~ Jan 25) to https://docs.datastax.com/en/pulsar-sink/docs/.  Between now and GA, it's a 404.

**Comment by chrislatimer** [comment]
Just to be clear on this, it looks like we're doing a simple text search on the docs for "mapping"? Do we have enough content planned in our docs to feel confident that this search will return "practical examples and usages of mapping" as stated in the readme?

**Comment by eolivelli** [comment]
> Just to be clear on this, it looks like we're doing a simple text search on the docs for "mapping"? Do we have enough content planned in our docs to feel confident that this search will return "practical examples and usages of mapping" as stated in the readme?

@chrislatimer 
I copied from the Kafka Sink
https://github.com/datastax/kafka-sink

**Comment by eolivelli** [comment]
@chrislatimer  @johnsmartco we should remove the link or change it to something more useful.

btw we can change it at anytime, as github shows the current master branch, no need to cut a release

**Comment by aymkhalil** [comment]
(cleaning up old issues, for now the link is up)
